// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/users": {
            "get": {
                "description": "Returns a list of all users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get all users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GetUserResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseModel"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a user with provided information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateUserRequestModel"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.CreateUserResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseModel"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CreateUserRequestModel": {
            "type": "object",
            "required": [
                "email",
                "mobile_number",
                "name",
                "pancard"
            ],
            "properties": {
                "age": {
                    "description": "optional",
                    "type": "integer",
                    "maximum": 120,
                    "minimum": 0,
                    "example": 18
                },
                "bio": {
                    "description": "optional",
                    "type": "string",
                    "example": "I am Harsh"
                },
                "birthday": {
                    "description": "optional, omitempty omits validations if it has no value",
                    "type": "string",
                    "example": "2001-04-30"
                },
                "email": {
                    "type": "string",
                    "example": "abd@gmail.com"
                },
                "mobile_number": {
                    "type": "string",
                    "example": "9898009898"
                },
                "name": {
                    "type": "string",
                    "example": "Harsh"
                },
                "pancard": {
                    "type": "string",
                    "example": "ABCDE12345"
                }
            }
        },
        "models.CreateUserResponseModel": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "message": {
                    "type": "string",
                    "example": "User created successfully"
                }
            }
        },
        "models.ErrorResponseModel": {
            "type": "object",
            "properties": {
                "errors": {
                    "description": "Optional field-level validation errors",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "email": "must be a valid email address"
                    }
                },
                "message": {
                    "description": "General message",
                    "type": "string",
                    "example": "invalid input data"
                }
            }
        },
        "models.GetUserResponseModel": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 25
                },
                "bio": {
                    "type": "string",
                    "example": "I'm Harsh"
                },
                "birthday": {
                    "type": "string",
                    "example": "2001-04-30"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2025-06-15 11:00:00"
                },
                "email": {
                    "type": "string",
                    "example": "abd@gmail.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "mobileNumber": {
                    "type": "string",
                    "example": "9898009898"
                },
                "name": {
                    "type": "string",
                    "example": "Harsh"
                },
                "pancard": {
                    "type": "string",
                    "example": "ABCDE12345"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2025-06-15 11:00:00"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "User API",
	Description:      "This is a sample server for managing users.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register("auth", SwaggerInfo)
}
