// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/watchlist/watchlists": {
            "get": {
                "description": "Returns a list of all watchlists",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Watchlists"
                ],
                "summary": "Get all watchlists",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GetWatchlistResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseModel"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a watchlist with provided information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Watchlists"
                ],
                "summary": "Create a new watchlist",
                "parameters": [
                    {
                        "description": "Watchlist data",
                        "name": "watchlist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateWatchlistRequestModel"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.CreateWatchlistResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseModel"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CreateWatchlistRequestModel": {
            "type": "object",
            "required": [
                "name",
                "userId"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Range Rover"
                },
                "userId": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.CreateWatchlistResponseModel": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Watchlist created"
                },
                "watchlistId": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.ErrorResponseModel": {
            "type": "object",
            "properties": {
                "errors": {
                    "description": "Optional field-level validation errors",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "name": "must be valid name"
                    }
                },
                "message": {
                    "description": "General message",
                    "type": "string",
                    "example": "invalid input data"
                }
            }
        },
        "models.GetWatchlistResponseModel": {
            "type": "object",
            "properties": {
                "watchlistId": {
                    "type": "integer",
                    "example": 1
                },
                "watchlistName": {
                    "type": "string",
                    "example": "Range Rover"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Watchlist API",
	Description:      "This is a sample server for managing watchlists.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register("watchlist", SwaggerInfo)
}
